services:
  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: ["postgres", "-p", "${POSTGRES_PORT}"]
    restart: always

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    env_file:
      - ./.env
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--port", "${REDIS_PORT}"]
    restart: always

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DEBUG=${DEBUG}
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres_data:
  redis_data: